from flask import Blueprint, session, redirect, url_for, flash, send_file, make_response
import io
import json

export_bp = Blueprint('export', __name__)


@export_bp.route('/export/docx')
def export_docx():
    """Generate and download a DOCX report from the current analysis data."""
    analysis = session.get('analysis')
    if not analysis:
        flash('No analysis data found. Please run an audit first.', 'error')
        return redirect(url_for('upload.upload_page'))

    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        flash('DOCX export requires python-docx. Install with: pip install python-docx', 'error')
        return redirect(url_for('report.report_page'))

    doc = Document()

    # --- Styles ---
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    # --- Title ---
    title = doc.add_heading('FairSight — Fairness Audit Report', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph('')

    # --- Metadata ---
    meta_table = doc.add_table(rows=4, cols=2)
    meta_table.style = 'Light Grid Accent 1'
    meta_data = [
        ('Dataset', analysis.get('dataset_name', 'N/A')),
        ('Analysis Date', analysis.get('analysis_timestamp', 'N/A')),
        ('Target Column', analysis.get('target_col', 'N/A')),
        ('Sensitive Attribute', analysis.get('sensitive_col', 'N/A'))
    ]
    for i, (label, value) in enumerate(meta_data):
        meta_table.rows[i].cells[0].text = label
        meta_table.rows[i].cells[1].text = str(value)

    doc.add_paragraph('')

    # --- AI Insight ---
    doc.add_heading('AI Insight', level=1)
    score = analysis.get('fairness_score', 0)
    di = analysis.get('disparate_impact', 0)
    sensitive = analysis.get('sensitive_col', 'N/A')
    target = analysis.get('target_col', 'N/A')

    if score < 50:
        insight = f"Significant disparity detected in {target} across {sensitive} groups. Disparate impact ratio is {di:.2f}. Immediate intervention required."
    elif score < 75:
        insight = f"Moderate differences found across {sensitive}. Disparate impact ratio is {di:.2f}, near the acceptable range but indicating potential underlying biases."
    else:
        insight = f"Dataset appears fair. Selection rate across {sensitive} groups is balanced, with a disparate impact ratio of {di:.2f}."

    doc.add_paragraph(insight)
    doc.add_paragraph('')

    # --- Key Metrics ---
    doc.add_heading('Key Metrics', level=1)

    metrics_table = doc.add_table(rows=4, cols=2)
    metrics_table.style = 'Light Grid Accent 1'
    verdict = analysis.get('verdict', 'unknown')
    verdict_text = 'High Bias' if verdict == 'biased' else ('Moderate Bias' if verdict == 'warning' else 'Fair')

    metrics = [
        ('Overall Fairness Score', f"{score} / 100"),
        ('Disparate Impact Ratio', f"{di:.4f}"),
        ('Verdict', verdict_text),
        ('Dataset Size', str(analysis.get('dataset_size', 'N/A')))
    ]
    for i, (label, value) in enumerate(metrics):
        metrics_table.rows[i].cells[0].text = label
        metrics_table.rows[i].cells[1].text = value

    doc.add_paragraph('')

    # --- Selection Rates ---
    doc.add_heading('Selection Rate by Group', level=1)

    parity = analysis.get('demographic_parity', {})
    if parity:
        rate_table = doc.add_table(rows=len(parity) + 1, cols=2)
        rate_table.style = 'Light Grid Accent 1'
        rate_table.rows[0].cells[0].text = 'Group'
        rate_table.rows[0].cells[1].text = 'Selection Rate'
        for i, (group, rate) in enumerate(parity.items(), 1):
            rate_table.rows[i].cells[0].text = str(group).title()
            rate_table.rows[i].cells[1].text = f"{rate * 100:.1f}%"
    else:
        doc.add_paragraph('No demographic parity data available.')

    doc.add_paragraph('')

    # --- Group Composition ---
    group_counts = analysis.get('group_counts', {})
    if group_counts:
        doc.add_heading('Dataset Composition', level=1)
        comp_table = doc.add_table(rows=len(group_counts) + 1, cols=2)
        comp_table.style = 'Light Grid Accent 1'
        comp_table.rows[0].cells[0].text = 'Group'
        comp_table.rows[0].cells[1].text = 'Count'
        for i, (group, count) in enumerate(group_counts.items(), 1):
            comp_table.rows[i].cells[0].text = str(group).title()
            comp_table.rows[i].cells[1].text = str(count)

    doc.add_paragraph('')
    doc.add_paragraph('— Report generated by FairSight AI Bias Detection Platform —').alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"FairSight_Report_{analysis.get('analysis_timestamp', 'report').replace(' ', '_').replace(':', '-')}.docx",
        mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )


@export_bp.route('/export/data')
def export_data():
    """Return analysis data as JSON for the PDF export client-side."""
    analysis = session.get('analysis')
    if not analysis:
        return {'error': 'No analysis data'}, 404
    return analysis
